modelname: "../rsc/digit/digit.urdf"
activation_key: "../share/raisim/activation.raisim"
enable_gravity: True
animation_mode: False
jointPgain: 50000000.0
jointDgain: 5000000000.0
# jointPgain: 1.0
# jointDgain: 15.0
