modelname: "../rsc/digit/digit.urdf"
activation_key: "../share/raisim/activation.raisim"
enable_gravity: True
animation_mode: True
#jointPgain: 100000.0
#jointDgain: 1000000.0
jointPgain: 100.0
jointDgain: 0.1
