modelname: "../rsc/nao/nao.urdf"
activation_key: "../share/raisim/activation.raisim"
enable_gravity: True
animation_mode: False
jointPgain: 150.0
jointDgain: 10.0
#jointPgain: 10000000.0
#jointDgain: 100000.0
